# 相关配置属性
# https://www.cnblogs.com/cx987514451/p/9318485.html

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
   username: root
   password: 1212210131
   driver-class-name: com.mysql.jdbc.Driver
 jpa:
   database: mysql
   database-platform: org.hibernate.dialect.MySQL5Dialect
   show-sql: true