spring:
   redis:
     host: localhost
     port: 6379
     password:
#     database: 1
#     timeout: 0
     pool:
     jedis:
       pool:
         max-active: 8
         max-wait: -1
         max-idle: 500
         min-idle: 0